// <auto-generated />
using System;
using Inventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Inventory.Data.Migrations
{
    [DbContext(typeof(AmCartDbContext))]
    [Migration("20201204080459_intial")]
    partial class intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Inventory.Core.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Brand");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 90, DateTimeKind.Utc).AddTicks(8452),
                            IsRemoved = false,
                            Name = "Arrow",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 90, DateTimeKind.Utc).AddTicks(8452)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 90, DateTimeKind.Utc).AddTicks(8452),
                            IsRemoved = false,
                            Name = "Raymond",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 90, DateTimeKind.Utc).AddTicks(8452)
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 90, DateTimeKind.Utc).AddTicks(8452),
                            IsRemoved = false,
                            Name = "Levi's",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 90, DateTimeKind.Utc).AddTicks(8452)
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 90, DateTimeKind.Utc).AddTicks(8452),
                            IsRemoved = false,
                            Name = "Allen Solly",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 90, DateTimeKind.Utc).AddTicks(8452)
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 90, DateTimeKind.Utc).AddTicks(8452),
                            IsRemoved = false,
                            Name = "Wrangler",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 90, DateTimeKind.Utc).AddTicks(8452)
                        });
                });

            modelBuilder.Entity("Inventory.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022),
                            IsRemoved = false,
                            Name = "Men",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022),
                            IsRemoved = false,
                            Name = "Women",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022)
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022),
                            IsRemoved = false,
                            Name = "Indian & Western Wear",
                            ParentId = 2,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022)
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022),
                            IsRemoved = false,
                            Name = "Western Wear",
                            ParentId = 2,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022)
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022),
                            IsRemoved = false,
                            Name = "Accessories",
                            ParentId = 2,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022)
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022),
                            IsRemoved = false,
                            Name = "Clothing",
                            ParentId = 1,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022)
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022),
                            IsRemoved = false,
                            Name = "Accessories",
                            ParentId = 1,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022)
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022),
                            IsRemoved = false,
                            Name = "Kurtas & Suits",
                            ParentId = 3,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022)
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022),
                            IsRemoved = false,
                            Name = "Kurtis & Tunics",
                            ParentId = 3,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022)
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022),
                            IsRemoved = false,
                            Name = "Dresses & Jumpsuits",
                            ParentId = 4,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022)
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022),
                            IsRemoved = false,
                            Name = "Tops, T-Shirts & Shirts",
                            ParentId = 4,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022)
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022),
                            IsRemoved = false,
                            Name = "Women Watches",
                            ParentId = 5,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022)
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022),
                            IsRemoved = false,
                            Name = "Analog",
                            ParentId = 5,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022)
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022),
                            IsRemoved = false,
                            Name = "T-Shirts",
                            ParentId = 6,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022)
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022),
                            IsRemoved = false,
                            Name = "Casual Shirts",
                            ParentId = 6,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022)
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022),
                            IsRemoved = false,
                            Name = "Watches & Wearables",
                            ParentId = 7,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022)
                        },
                        new
                        {
                            Id = 17,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022),
                            IsRemoved = false,
                            Name = "Sunglasses & Frames",
                            ParentId = 7,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 92, DateTimeKind.Utc).AddTicks(8022)
                        });
                });

            modelBuilder.Entity("Inventory.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 8,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = "Pink embroidered kurta with sharara and dupatta",
                            IsRemoved = false,
                            Name = "Women Pink Embroidered Kurta",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            CategoryId = 9,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = "Blue and Coral pink floral print straight kurti, has a round neck, long sleeves, straight hem, and side slits",
                            IsRemoved = false,
                            Name = "Women Blue & Coral Pink Floral Print Straight Kurti",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            CategoryId = 10,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = "Blue printed woven A-line dress, has shoulder straps, sleeveless, concealed zip closure, and flared hem",
                            IsRemoved = false,
                            Name = "Women Blue Printed A-Line Dress",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 4,
                            CategoryId = 11,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = "Black solid woven victorian crop fitted top with gathers, has a sweetheart neck, long cuffed sleeves, and button closures",
                            IsRemoved = false,
                            Name = "Women Black Solid Victorian Crop Fitted Top",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 5,
                            CategoryId = 12,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = "Rose Gold - Toned bracelet style,stainless steel strap with a foldover closure",
                            IsRemoved = false,
                            Name = "Women Rose Gold Watch",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 1,
                            CategoryId = 13,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = "Silver-Toned regular, stainless steel strap with a foldover closure",
                            IsRemoved = false,
                            Name = "Women Silver-Toned Embellished Analogue Watch",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            CategoryId = 14,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = "White and Black printed T-shirt, has a round neck, and short sleeves",
                            IsRemoved = false,
                            Name = "Men White & Black Printed Round Neck T-shirt",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 3,
                            CategoryId = 15,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = "Orange solid casual shirt, has a button-down collar, long sleeves, button placket, curved hem, and 1 patch pocket",
                            IsRemoved = false,
                            Name = "Men Orange Regular Fit Solid Casual Shirt",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 4,
                            CategoryId = 16,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = " latest smartwatch with a stylish new design and a gorgeous 1.3\" full touch colour display.",
                            IsRemoved = false,
                            Name = "Men Black Active Smartwatch",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 5,
                            CategoryId = 17,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = "UV Protected Lens with full rim",
                            IsRemoved = false,
                            Name = "Men Oval Sunglasses",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 1,
                            CategoryId = 8,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = "Coral Orange printed straight kurta, has a mandarin collar, three-quarter sleeves, straight hem, and side slits",
                            IsRemoved = false,
                            Name = "Women Coral Orange Printed Straight Kurta",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 2,
                            CategoryId = 9,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = "Rust Red printed Tunic, has a mandarin collar, three-quarter sleeves, and button closure",
                            IsRemoved = false,
                            Name = "Women Rust Red Printed Tunic",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 3,
                            CategoryId = 10,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = "Yellow solid woven maxi dress, has shoulder straps, sleeveless, concealed zip closure, and flared hem",
                            IsRemoved = false,
                            Name = "Women Yellow Solid Wrap Maxi Dress",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 4,
                            CategoryId = 11,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = "Sea Green self-design woven empire top, has a V-neck, and three-quarter sleeves",
                            IsRemoved = false,
                            Name = "Women Sea Green Self Design Empire Top",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 5,
                            CategoryId = 12,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = " Silver-Toned bracelet style, stainless steel strap with a foldover closure",
                            IsRemoved = false,
                            Name = "Women Charcoal Grey Watch",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 1,
                            CategoryId = 13,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = "Silver-Toned bracelet style, stainless steel strap with a foldover closure",
                            IsRemoved = false,
                            Name = "Premium Women Silver-Toned Analogue Watch",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 2,
                            CategoryId = 14,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = "Blue printed T-shirt, has a round neck, and short sleeves",
                            IsRemoved = false,
                            Name = "Men Blue Printed Round Neck T-shirt",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 3,
                            CategoryId = 15,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = "Navy Blue and White checked casual shirt, has a spread collar, short sleeves, button placket, and curved hem",
                            IsRemoved = false,
                            Name = "Men Navy Blue & White Slim Fit Checked Casual Shirt",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 4,
                            CategoryId = 16,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = "Grey smart watch, has a grey stainless steel foldover strap 40mm Explorist HR touchscreen",
                            IsRemoved = false,
                            Name = "Men Grey Explorist HR Smartwatch",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 5,
                            CategoryId = 17,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508),
                            Description = "Metallic oval full frame, has printed branding and printed detail on the inner side of both the arms, and plastic casings on the arms",
                            IsRemoved = false,
                            Name = "Men Aviator Sunglasses",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 94, DateTimeKind.Utc).AddTicks(2508)
                        });
                });

            modelBuilder.Entity("Inventory.Core.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 1,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 2,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 3,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 4,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 5,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 6,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 7,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 8,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 9,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 10,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 11,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 12,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 13,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 14,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 15,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 16,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 17,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 17,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 18,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 18,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 19,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 19,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        },
                        new
                        {
                            Id = 20,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874),
                            ImageURL = "https://m.media-amazon.com/images/I/41ImsZy3u5L.__AC_SY200_.jpg",
                            IsRemoved = false,
                            ProductId = 20,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(874)
                        });
                });

            modelBuilder.Entity("Inventory.Core.Models.ProductMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductMetadata");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 1,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 2,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 3,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 4,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 5,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 6,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 7,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 8,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 9,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 10,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 11,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 12,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 13,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 14,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 15,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 16,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 17,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 17,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 18,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 18,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 19,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 19,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        },
                        new
                        {
                            Id = 20,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            IsRemoved = false,
                            ProductId = 20,
                            Type = "Price",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 97, DateTimeKind.Utc).AddTicks(9648),
                            Value = "100"
                        });
                });

            modelBuilder.Entity("Inventory.Core.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("VendorId");

                    b.ToTable("Purchase");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 1,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 2,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 3,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 4,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 5,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 6,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 7,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 8,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 9,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 4
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 10,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 5
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 11,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 12,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 13,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 3
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 14,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 4
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 15,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 5
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 16,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 17,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 18,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 3
                        },
                        new
                        {
                            Id = 19,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 19,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 4
                        },
                        new
                        {
                            Id = 20,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            IsRemoved = false,
                            ProductId = 20,
                            PurchasedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 95, DateTimeKind.Utc).AddTicks(4699),
                            VendorId = 5
                        });
                });

            modelBuilder.Entity("Inventory.Core.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Stock");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 1,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 2,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 3,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 4,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 5,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 6,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 7,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 8,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 9,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 10,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 11,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 12,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 13,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 14,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 15,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 16,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 17,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 17,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 18,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 18,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 19,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 19,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        },
                        new
                        {
                            Id = 20,
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979),
                            IsRemoved = false,
                            ProductId = 20,
                            Quantity = 100,
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 96, DateTimeKind.Utc).AddTicks(2979)
                        });
                });

            modelBuilder.Entity("Inventory.Core.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Vendor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "India",
                            Contact = "1234567890",
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 93, DateTimeKind.Utc).AddTicks(2457),
                            IsRemoved = false,
                            Name = "Pattern Dynamics",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 93, DateTimeKind.Utc).AddTicks(2457)
                        },
                        new
                        {
                            Id = 2,
                            Address = "India",
                            Contact = "1234567890",
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 93, DateTimeKind.Utc).AddTicks(2457),
                            IsRemoved = false,
                            Name = "JD Corp",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 93, DateTimeKind.Utc).AddTicks(2457)
                        },
                        new
                        {
                            Id = 3,
                            Address = "India",
                            Contact = "1234567890",
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 93, DateTimeKind.Utc).AddTicks(2457),
                            IsRemoved = false,
                            Name = "Lotus Knits",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 93, DateTimeKind.Utc).AddTicks(2457)
                        },
                        new
                        {
                            Id = 4,
                            Address = "India",
                            Contact = "1234567890",
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 93, DateTimeKind.Utc).AddTicks(2457),
                            IsRemoved = false,
                            Name = "House of Attuendo",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 93, DateTimeKind.Utc).AddTicks(2457)
                        },
                        new
                        {
                            Id = 5,
                            Address = "India",
                            Contact = "1234567890",
                            CreatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 93, DateTimeKind.Utc).AddTicks(2457),
                            IsRemoved = false,
                            Name = "Sreepriya Exports Pvt Ltd",
                            UpdatedOn = new DateTime(2020, 12, 4, 8, 4, 59, 93, DateTimeKind.Utc).AddTicks(2457)
                        });
                });

            modelBuilder.Entity("Inventory.Core.Models.Category", b =>
                {
                    b.HasOne("Inventory.Core.Models.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Inventory.Core.Models.Product", b =>
                {
                    b.HasOne("Inventory.Core.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory.Core.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory.Core.Models.ProductImage", b =>
                {
                    b.HasOne("Inventory.Core.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory.Core.Models.ProductMetadata", b =>
                {
                    b.HasOne("Inventory.Core.Models.Product", "Product")
                        .WithMany("ProductMetadataList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory.Core.Models.Purchase", b =>
                {
                    b.HasOne("Inventory.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory.Core.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory.Core.Models.Stock", b =>
                {
                    b.HasOne("Inventory.Core.Models.Product", "Product")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
